services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-exosphere
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
      TYPE: "NEOFORGE"
      NEOFORGE_VERSION: "21.1.219"
      ONLINE_MODE: "FALSE"
      # Java usar√° 4GB para el juego
      MEMORY: "4G"
    volumes:
      # Mapea tu carpeta a los datos del servidor
      - .:/data
    deploy:
      resources:
        limits:
          cpus: '2.0'
          # Docker permite hasta 6GB para evitar el error 137
          memory: 6G
    restart: unless-stopped