services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-proyecto-japon
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      TYPE: "FORGE"
      FORGE_VERSION: "LATEST"
      ONLINE_MODE: "FALSE"
      # Bajamos a 3500M para dar aire a la VPS
      MEMORY: "3500M" 
      JVM_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20"
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          # Bajamos el limite total a 5G
          memory: 5G