services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-proyecto-japon
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      TYPE: "FORGE"
      FORGE_VERSION: "LATEST"
      ONLINE_MODE: "FALSE"
      LEVEL: "world_japon"
      # Asignación de memoria balanceada para VPS de 8GB
      MEMORY: "3000M" 
      JVM_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20"
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          # Límite físico estricto para proteger el resto de la VPS
          memory: 4500M